### ISSUE TITLE
Issue building boost on windows 10

### ISSUE THREAD

**Issue by JasonDictos** [hunter-packages/boost#2]
So for some reason boost is failing to build, the bootstrap.log (attached) file shows this error:

* I've created SSCCE GitHub repository to reproduce the issue: https://github.com/JasonDictos/dictos 

I've checked that the first error in logs **IS NOT** `external.build.failed`. **[No]**

It is an external build failure...

* I'm building on [Windows 10 x64].
* [I'm using official CMake release]
* CMake version: <3.11.0>

* I'm not using toolchain
* I'm using unmodified toolchain Visual Studio 2015 Win64 from cmake )

I'm using next command line on generate step:
```
cmake -H. -B_build -G"Visual Studio 15 2017 Win64" -DHUNTER_STATUS_DEBUG=ON
```

---

[build_log.txt](https://github.com/hunter-packages/boost/files/1911062/build_log.txt)
[boost_build_log.txt](https://github.com/hunter-packages/boost/files/1911064/boost_build_log.txt)
[bootstrap.log](https://github.com/hunter-packages/boost/files/1911065/bootstrap.log)

**Comment by ruslo** [comment]
> [I'm using system CMake|I'm using official CMake release|]

It's supposed that you will choose one :) As far as I can see it's `I'm using official CMake release` for you.

**Comment by JasonDictos** [comment]
Fixed!

**Comment by ruslo** [comment]
So to summarize it's a error inside Boost while it tried to build b2:
```
[MKDIR] bin.ntx86_64
A subdirectory or file bin.ntx86_64 already exists.

    md "bin.ntx86_64"

...failed [MKDIR] bin.ntx86_64...
```

Try to run your setup in clean AppVeyor environment.

**Comment by JasonDictos** [comment]
Alright running an AppVeyor build now

**Comment by JasonDictos** [comment]
https://ci.appveyor.com/project/JasonDictos/dictos

**Comment by JasonDictos** [comment]
Appears to have proceeded past the part where it fails locally

**Comment by ruslo** [comment]
It may mean that something wrong with your local environment. Try to remove Hunter directory, turn off antivirus software, restart, etc.

**Comment by ruslo** [comment]
The only reference I have found about the Boost error message:
* https://github.com/qbittorrent/qBittorrent/issues/4589#issuecomment-298168661

**Comment by JasonDictos** [comment]
Huh interesting, well I just re-installed windows on this desktop, nothing too crazy is going on here, guess its time to put on my big boy pants and debug it huh ;)

**Comment by ruslo** [comment]
Try it without Hunter. Open developer command prompt, enter Boost build directory inside Hunter and run `bootstrap.bat`.

**Comment by JasonDictos** [comment]
c:\.hunter\_Base\b49c4b5\b94518a\e338239\Build\Boost\Source>bootstrap.bat
Building Boost.Build engine

Failed to build Boost.Build engine.
Please consult bootstrap.log for further diagnostics.

You can try to obtain a prebuilt binary from

   http://sf.net/project/showfiles.php?group_id=7586&package_id=72941

Also, you can file an issue at http://svn.boost.org
Please attach bootstrap.log in that case.

c:\.hunter\_Base\b49c4b5\b94518a\e338239\Build\Boost\Source>dir
 Volume in drive C has no label.
 Volume Serial Number is AE93-A23D

 Directory of c:\.hunter\_Base\b49c4b5\b94518a\e338239\Build\Boost\Source

04/15/2018  10:33 AM    <DIR>          .
04/15/2018  10:33 AM    <DIR>          ..
12/13/2017  05:36 PM    <DIR>          boost
12/13/2017  04:56 PM               867 boost-build.jam
12/13/2017  04:56 PM             1,054 boost.css
12/13/2017  04:56 PM             6,308 boost.png
12/13/2017  04:56 PM            23,453 boostcpp.jam
12/13/2017  04:56 PM             2,558 bootstrap.bat
04/15/2018  11:36 AM             8,665 bootstrap.log
12/13/2017  04:56 PM            10,598 bootstrap.sh
12/13/2017  05:04 PM    <DIR>          doc
12/13/2017  04:56 PM               794 index.htm
12/13/2017  05:36 PM             5,614 index.html
12/13/2017  04:56 PM               298 INSTALL
12/13/2017  04:56 PM            11,933 Jamroot
12/13/2017  05:36 PM    <DIR>          libs
12/13/2017  04:56 PM             1,361 LICENSE_1_0.txt
12/13/2017  04:56 PM    <DIR>          more
04/15/2018  10:33 AM               431 patched_boostrap.bat
12/13/2017  04:56 PM             2,757 rst.css
12/13/2017  04:56 PM    <DIR>          status
12/13/2017  04:56 PM    <DIR>          tools
              14 File(s)         76,691 bytes
               8 Dir(s)  389,755,371,520 bytes free

c:\.hunter\_Base\b49c4b5\b94518a\e338239\Build\Boost\Source>

c:\.hunter\_Base\b49c4b5\b94518a\e338239\Build\Boost\Source\tools\build\src\engine>.\bootstrap\jam0 -f build.jam --toolset=vc141 "--toolset-root=C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\Tools\..\..\VC\ "
...found 161 targets...
...updating 3 targets...
[MKDIR] bin.ntx86
[COMPILE] bin.ntx86\b2.exe
command.c
c1: fatal error C1083: Cannot open source file: 'command.c': No such file or directory
compile.c
c1: fatal error C1083: Cannot open source file: 'compile.c': No such file or directory
constants.c
c1: fatal error C1083: Cannot open source file: 'constants.c': No such file or directory
debug.c
c1: fatal error C1083: Cannot open source file: 'debug.c': No such file or directory
debugger.c
c1: fatal error C1083: Cannot open source file: 'debugger.c': No such file or directory
execcmd.c
c1: fatal error C1083: Cannot open source file: 'execcmd.c': No such file or directory
frames.c
c1: fatal error C1083: Cannot open source file: 'frames.c': No such file or directory
function.c
c1: fatal error C1083: Cannot open source file: 'function.c': No such file or directory
glob.c
c1: fatal error C1083: Cannot open source file: 'glob.c': No such file or directory
hash.c
c1: fatal error C1083: Cannot open source file: 'hash.c': No such file or directory
hcache.c
c1: fatal error C1083: Cannot open source file: 'hcache.c': No such file or directory
headers.c
c1: fatal error C1083: Cannot open source file: 'headers.c': No such file or directory
hdrmacro.c
c1: fatal error C1083: Cannot open source file: 'hdrmacro.c': No such file or directory
jam.c
c1: fatal error C1083: Cannot open source file: 'jam.c': No such file or directory
jambase.c
c1: fatal error C1083: Cannot open source file: 'jambase.c': No such file or directory
jamgram.c
c1: fatal error C1083: Cannot open source file: 'jamgram.c': No such file or directory
lists.c
c1: fatal error C1083: Cannot open source file: 'lists.c': No such file or directory
make.c
c1: fatal error C1083: Cannot open source file: 'make.c': No such file or directory
make1.c
c1: fatal error C1083: Cannot open source file: 'make1.c': No such file or directory
mem.c
c1: fatal error C1083: Cannot open source file: 'mem.c': No such file or directory
Compiling...
object.c
c1: fatal error C1083: Cannot open source file: 'object.c': No such file or directory
option.c
c1: fatal error C1083: Cannot open source file: 'option.c': No such file or directory
output.c
c1: fatal error C1083: Cannot open source file: 'output.c': No such file or directory
parse.c
c1: fatal error C1083: Cannot open source file: 'parse.c': No such file or directory
pathsys.c
c1: fatal error C1083: Cannot open source file: 'pathsys.c': No such file or directory
regexp.c
c1: fatal error C1083: Cannot open source file: 'regexp.c': No such file or directory
rules.c
c1: fatal error C1083: Cannot open source file: 'rules.c': No such file or directory
scan.c
c1: fatal error C1083: Cannot open source file: 'scan.c': No such file or directory
search.c
c1: fatal error C1083: Cannot open source file: 'search.c': No such file or directory
subst.c
c1: fatal error C1083: Cannot open source file: 'subst.c': No such file or directory
w32_getreg.c
c1: fatal error C1083: Cannot open source file: 'w32_getreg.c': No such file or directory
timestamp.c
c1: fatal error C1083: Cannot open source file: 'timestamp.c': No such file or directory
variable.c
c1: fatal error C1083: Cannot open source file: 'variable.c': No such file or directory
modules.c
c1: fatal error C1083: Cannot open source file: 'modules.c': No such file or directory
strings.c
c1: fatal error C1083: Cannot open source file: 'strings.c': No such file or directory
filesys.c
c1: fatal error C1083: Cannot open source file: 'filesys.c': No such file or directory
builtins.c
c1: fatal error C1083: Cannot open source file: 'builtins.c': No such file or directory
class.c
c1: fatal error C1083: Cannot open source file: 'class.c': No such file or directory
cwd.c
c1: fatal error C1083: Cannot open source file: 'cwd.c': No such file or directory
native.c
c1: fatal error C1083: Cannot open source file: 'native.c': No such file or directory
Compiling...
md5.c
c1: fatal error C1083: Cannot open source file: 'md5.c': No such file or directory
set.c
c1: fatal error C1083: Cannot open source file: 'modules\set.c': No such file or directory
path.c
c1: fatal error C1083: Cannot open source file: 'modules\path.c': No such file or directory
regex.c
c1: fatal error C1083: Cannot open source file: 'modules\regex.c': No such file or directory
property-set.c
c1: fatal error C1083: Cannot open source file: 'modules\property-set.c': No such file or directory
sequence.c
c1: fatal error C1083: Cannot open source file: 'modules\sequence.c': No such file or directory
order.c
c1: fatal error C1083: Cannot open source file: 'modules\order.c': No such file or directory
execnt.c
c1: fatal error C1083: Cannot open source file: 'execnt.c': No such file or directory
filent.c
c1: fatal error C1083: Cannot open source file: 'filent.c': No such file or directory
pathnt.c
c1: fatal error C1083: Cannot open source file: 'pathnt.c': No such file or directory

    "cl"  "/Fdbin.ntx86/" "/Fobin.ntx86/" /Febin.ntx86\b2.exe "-DNDEBUG" "-DOPT_HEADER_CACHE_EXT" "-DOPT_GRAPH_DEBUG_EXT" "-DOPT_SEMAPHORE" "-DOPT_AT_FILES" "-DOPT_DEBUG_PROFILE" "-DJAM_DEBUGGER" "-DOPT_FIX_TARGET_VARIABLES_EXT" "-DOPT_IMPROVED_PATIENCE_EXT" "-DNT" "-DYYSTACKSIZE=5000" "/nologo" "/GL" "/MT" "/O2" "/Ob2" "/Gy" "/GF" "/GA" "/wd4996" "command.c" "compile.c" "constants.c" "debug.c" "debugger.c" "execcmd.c" "frames.c" "function.c" "glob.c" "hash.c" "hcache.c" "headers.c" "hdrmacro.c" "jam.c" "jambase.c" "jamgram.c" "lists.c" "make.c" "make1.c" "mem.c" "object.c" "option.c" "output.c" "parse.c" "pathsys.c" "regexp.c" "rules.c" "scan.c" "search.c" "subst.c" "w32_getreg.c" "timestamp.c" "variable.c" "modules.c" "strings.c" "filesys.c" "builtins.c" "class.c" "cwd.c" "native.c" "md5.c" "modules\set.c" "modules\path.c" "modules\regex.c" "modules\property-set.c" "modules\sequence.c" "modules\order.c" "execnt.c" "filent.c" "pathnt.c" "kernel32.lib" "advapi32.lib" "user32.lib"

...failed [COMPILE] bin.ntx86\b2.exe...
...skipped bjam.exe for lack of b2.exe...
...failed updating 1 target...
...skipped 1 target...
...updated 1 target...

c:\.hunter\_Base\b49c4b5\b94518a\e338239\Build\Boost\Source\tools\build\src\engine>exit /b 1

c:\.hunter\_Base\b49c4b5\b94518a\e338239\Build\Boost\Source>

**Comment by JasonDictos** [comment]
Hmm it appears that this block in the bat file cannot locate the tools, the dir bin.ntx86_64 does not exist:

if exist ".\tools\build\src\engine\bin.ntx86\bjam.exe" (
   copy .\tools\build\src\engine\bin.ntx86\b2.exe . > nul
   copy .\tools\build\src\engine\bin.ntx86\bjam.exe . > nul
   goto :bjam_built)

if exist ".\tools\build\src\engine\bin.ntx86_64\bjam.exe" (
   copy .\tools\build\src\engine\bin.ntx86_64\b2.exe . > nul
   copy .\tools\build\src\engine\bin.ntx86_64\bjam.exe . > nul
   goto :bjam_built)

goto :bjam_failure

**Comment by JasonDictos** [comment]
Is there a way I can try 1.67?

**Comment by ruslo** [comment]
It's not in Hunter yet, I can make an update. For now you can download sources yourself from https://www.boost.org/. It's really just unpack and call `bootstrap.bat`.

**Comment by JasonDictos** [comment]
Right, same error when I run it after extracting it. Ok close this issue I'll follow up with the boost guys. Thanks for all the help!

**Comment by JasonDictos** [comment]
Hmm procmon shows the activity:

12:14:59.6695400 PM	cmd.exe	14024	CreateFile	C:\temp\boost_1_67_0\boost_1_67_0\tools\build\src\engine\bin.ntx86	Desired Access: Read Data/List Directory, Synchronize, Disposition: Open, Options: Directory, Synchronous IO Non-Alert, Attributes: n/a, ShareMode: Read, Write, Delete, AllocationSize: n/a	NAME NOT FOUND
12:14:59.6698579 PM	cmd.exe	14024	CreateFile	C:\temp\boost_1_67_0\boost_1_67_0\tools\build\src\engine\bin.ntx86	Desired Access: Read Data/List Directory, Synchronize, Disposition: Open, Options: Directory, Synchronous IO Non-Alert, Attributes: n/a, ShareMode: Read, Write, Delete, AllocationSize: n/a	NAME NOT FOUND
12:14:59.6702030 PM	cmd.exe	14024	CreateFile	C:\temp\boost_1_67_0\boost_1_67_0\tools\build\src\engine\bin.ntx86_64	Desired Access: Read Data/List Directory, Synchronize, Disposition: Open, Options: Directory, Synchronous IO Non-Alert, Attributes: n/a, ShareMode: Read, Write, Delete, AllocationSize: n/a	NAME NOT FOUND
12:14:59.6705183 PM	cmd.exe	14024	CreateFile	C:\temp\boost_1_67_0\boost_1_67_0\tools\build\src\engine\bin.ntx86_64	Desired Access: Read Data/List Directory, Synchronize, Disposition: Open, Options: Directory, Synchronous IO Non-Alert, Attributes: n/a, ShareMode: Read, Write, Delete, AllocationSize: n/a	NAME NOT FOUND
12:15:12.3332451 PM	cmd.exe	18304	CreateFile	C:\code\bin.ntx86	Desired Access: Read Data/List Directory, Synchronize, Disposition: Create, Options: Directory, Synchronous IO Non-Alert, Open Reparse Point, Attributes: N, ShareMode: Read, Write, AllocationSize: 0	NAME COLLISION
12:15:12.3354936 PM	jam0.exe	18164	CreateFile	C:\temp\boost_1_67_0\boost_1_67_0\tools\build\src\engine\bin.ntx86	Desired Access: Read Attributes, Delete, Disposition: Open, Options: Non-Directory File, Open Reparse Point, Attributes: n/a, ShareMode: Read, Write, Delete, AllocationSize: n/a	NAME NOT FOUND
12:15:12.3457346 PM	cmd.exe	14024	CreateFile	C:\temp\boost_1_67_0\boost_1_67_0\tools\build\src\engine\bin.ntx86	Desired Access: Read Data/List Directory, Synchronize, Disposition: Open, Options: Directory, Synchronous IO Non-Alert, Attributes: n/a, ShareMode: Read, Write, Delete, AllocationSize: n/a	NAME NOT FOUND
12:15:12.3461763 PM	cmd.exe	14024	CreateFile	C:\temp\boost_1_67_0\boost_1_67_0\tools\build\src\engine\bin.ntx86_64	Desired Access: Read Data/List Directory, Synchronize, Disposition: Open, Options: Directory, Synchronous IO Non-Alert, Attributes: n/a, ShareMode: Read, Write, Delete, AllocationSize: n/a	NAME NOT FOUND

For some reason it tries to create the bin.ntx86 dir in the c:\code path

**Comment by ruslo** [comment]
> Right, same error when I run it after extracting it. Ok close this issue I'll follow up with the boost guys. Thanks for all the help!

If you will get any useful info please leave it in this page:
* https://docs.hunter.sh/en/latest/packages/pkg/Boost.html

**Comment by JasonDictos** [comment]
Oh damn I know what the problem is, I had set a registry key to set the current dir of command. I remember reading that it would change the CWD anytime a cmd was invoked, now it makes sense why thats a bad idea haha.

The key in question is:
Computer\HKEY_CURRENT_USER\Software\Microsoft\Command Processor\Autorun

I had place 'cd c:\code' there.
