### ISSUE TITLE
Failed to build x86_64 arch

### ISSUE THREAD

**Issue by olliwang** [hunter-packages/boost#3]
Hi, I was trying to build `boost_filesystem` and `boost_system` for my Android app. By default, Android Studio builds all of `armeabi-v7a`, `arm64-v8a`, `x86` and `x86_64` [ABIs](https://developer.android.com/ndk/guides/abis).

However, when building for `x86_64` it always failed with the following (related) error messages.

    /Users/username/Library/Android/sdk/ndk-bundle/toolchains/x86_64-4.9/prebuilt/darwin-x86_64/lib/gcc/x86_64-linux-android/4.9.x/../../../../x86_64-linux-android/bin/ld: error: /Users/username/.hunter/_Base/18cdbf5/7073908/6481172/Install/lib/libboost_filesystem-mt.a(unique_path.o): incompatible target
    /Users/username/Library/Android/sdk/ndk-bundle/toolchains/x86_64-4.9/prebuilt/darwin-x86_64/lib/gcc/x86_64-linux-android/4.9.x/../../../../x86_64-linux-android/bin/ld: error: /Users/username/.hunter/_Base/18cdbf5/7073908/6481172/Install/lib/libboost_system-mt.a(error_code.o): incompatible target
    /Users/username/.hunter/_Base/18cdbf5/7073908/6481172/Install/include/boost/filesystem/operations.hpp:451: error: undefined reference to 'boost::filesystem::detail::status(boost::filesystem::path const&, boost::system::error_code*)'
    /Users/username/.hunter/_Base/18cdbf5/7073908/6481172/Install/include/boost/filesystem/operations.hpp:572: error: undefined reference to 'boost::filesystem::detail::create_directory(boost::filesystem::path const&, boost::system::error_code*)'
    /Users/username/.hunter/_Base/18cdbf5/7073908/6481172/Install/include/boost/filesystem/path.hpp:792: error: undefined reference to 'boost::filesystem::path::operator/=(boost::filesystem::path const&)'
    /Users/username/.hunter/_Base/18cdbf5/7073908/6481172/Install/include/boost/filesystem/operations.hpp:451: error: undefined reference to 'boost::filesystem::detail::status(boost::filesystem::path const&, boost::system::error_code*)'
    /Users/username/.hunter/_Base/18cdbf5/7073908/6481172/Install/include/boost/filesystem/operations.hpp:572: error: undefined reference to 'boost::filesystem::detail::create_directory(boost::filesystem::path const&, boost::system::error_code*)'
    /Users/username/.hunter/_Base/18cdbf5/7073908/6481172/Install/include/boost/filesystem/operations.hpp:451: error: undefined reference to 'boost::filesystem::detail::status(boost::filesystem::path const&, boost::system::error_code*)'
    /Users/username/.hunter/_Base/18cdbf5/7073908/6481172/Install/include/boost/filesystem/operations.hpp:572: error: undefined reference to 'boost::filesystem::detail::create_directory(boost::filesystem::path const&, boost::system::error_code*)'
    /Users/username/.hunter/_Base/18cdbf5/7073908/6481172/Install/include/boost/filesystem/operations.hpp:451: error: undefined reference to 'boost::filesystem::detail::status(boost::filesystem::path const&, boost::system::error_code*)'
    /Users/username/.hunter/_Base/18cdbf5/7073908/6481172/Install/include/boost/filesystem/operations.hpp:572: error: undefined reference to 'boost::filesystem::detail::create_directory(boost::filesystem::path const&, boost::system::error_code*)'
    /Users/username/.hunter/_Base/18cdbf5/7073908/6481172/Install/include/boost/filesystem/operations.hpp:671: error: undefined reference to 'boost::filesystem::detail::remove_all(boost::filesystem::path const&, boost::system::error_code*)'
    /Users/username/.hunter/_Base/18cdbf5/7073908/6481172/Install/include/boost/filesystem/operations.hpp:664: error: undefined reference to 'boost::filesystem::detail::remove(boost::filesystem::path const&, boost::system::error_code*)'
    /Users/username/.hunter/_Base/18cdbf5/7073908/6481172/Install/include/boost/filesystem/operations.hpp:671: error: undefined reference to 'boost::filesystem::detail::remove_all(boost::filesystem::path const&, boost::system::error_code*)'
    /Users/username/.hunter/_Base/18cdbf5/7073908/6481172/Install/include/boost/filesystem/operations.hpp:723: error: undefined reference to 'boost::filesystem::detail::unique_path(boost::filesystem::path const&, boost::system::error_code*)'
    /Users/username/.hunter/_Base/18cdbf5/7073908/6481172/Install/include/boost/system/error_code.hpp:449: error: undefined reference to 'boost::system::system_category()'
    /Users/username/.hunter/_Base/18cdbf5/7073908/6481172/Install/include/boost/filesystem/operations.hpp:681: error: undefined reference to 'boost::filesystem::detail::rename(boost::filesystem::path const&, boost::filesystem::path const&, boost::system::error_code*)'
    /Users/username/.hunter/_Base/18cdbf5/7073908/6481172/Install/include/boost/filesystem/operations.hpp:664: error: undefined reference to 'boost::filesystem::detail::remove(boost::filesystem::path const&, boost::system::error_code*)'
    /Users/username/.hunter/_Base/18cdbf5/7073908/6481172/Install/include/boost/filesystem/operations.hpp:671: error: undefined reference to 'boost::filesystem::detail::remove_all(boost::filesystem::path const&, boost::system::error_code*)'
    /Users/username/.hunter/_Base/18cdbf5/7073908/6481172/Install/include/boost/filesystem/operations.hpp:671: error: undefined reference to 'boost::filesystem::detail::remove_all(boost::filesystem::path const&, boost::system::error_code*)'
    /Users/username/.hunter/_Base/18cdbf5/7073908/6481172/Install/include/boost/filesystem/operations.hpp:637: error: undefined reference to 'boost::filesystem::detail::last_write_time(boost::filesystem::path const&, boost::system::error_code*)'
    /Users/username/.hunter/_Base/18cdbf5/7073908/6481172/Install/include/boost/system/error_code.hpp:449: error: undefined reference to 'boost::system::system_category()'
    /Users/username/.hunter/_Base/18cdbf5/7073908/6481172/Install/include/boost/filesystem/operations.hpp:550: error: undefined reference to 'boost::filesystem::detail::copy_file(boost::filesystem::path const&, boost::filesystem::path const&, boost::filesystem::detail::copy_option, boost::system::error_code*)'
    /Users/username/.hunter/_Base/18cdbf5/7073908/6481172/Install/include/boost/filesystem/operations.hpp:637: error: undefined reference to 'boost::filesystem::detail::last_write_time(boost::filesystem::path const&, boost::system::error_code*)'
    /Users/username/.hunter/_Base/18cdbf5/7073908/6481172/Install/include/boost/filesystem/operations.hpp:644: error: undefined reference to 'boost::filesystem::detail::last_write_time(boost::filesystem::path const&, long, boost::system::error_code*)'
    /Users/username/.hunter/_Base/18cdbf5/7073908/6481172/Install/include/boost/filesystem/operations.hpp:664: error: undefined reference to 'boost::filesystem::detail::remove(boost::filesystem::path const&, boost::system::error_code*)'
    /Users/username/.hunter/_Base/18cdbf5/7073908/6481172/Install/include/boost/filesystem/operations.hpp:644: error: undefined reference to 'boost::filesystem::detail::last_write_time(boost::filesystem::path const&, long, boost::system::error_code*)'
    /Users/username/.hunter/_Base/18cdbf5/7073908/6481172/Install/include/boost/filesystem/operations.hpp:644: error: undefined reference to 'boost::filesystem::detail::last_write_time(boost::filesystem::path const&, long, boost::system::error_code*)'
    /Users/username/.hunter/_Base/18cdbf5/7073908/6481172/Install/include/boost/filesystem/operations.hpp:644: error: undefined reference to 'boost::filesystem::detail::last_write_time(boost::filesystem::path const&, long, boost::system::error_code*)'
    /Users/username/.hunter/_Base/18cdbf5/7073908/6481172/Install/include/boost/filesystem/operations.hpp:664: error: undefined reference to 'boost::filesystem::detail::remove(boost::filesystem::path const&, boost::system::error_code*)'
    /Users/username/.hunter/_Base/18cdbf5/7073908/6481172/Install/include/boost/filesystem/operations.hpp:637: error: undefined reference to 'boost::filesystem::detail::last_write_time(boost::filesystem::path const&, boost::system::error_code*)'
    /Users/username/.hunter/_Base/18cdbf5/7073908/6481172/Install/include/boost/filesystem/operations.hpp:637: error: undefined reference to 'boost::filesystem::detail::last_write_time(boost::filesystem::path const&, boost::system::error_code*)'
    /Users/username/workspace/fogofworld2/app/fogofworld/core/sync.cc:499: error: undefined reference to 'boost::filesystem::path::filename() const'
    /Users/username/.hunter/_Base/18cdbf5/7073908/6481172/Install/include/boost/filesystem/operations.hpp:939: error: undefined reference to 'boost::filesystem::detail::directory_iterator_increment(boost::filesystem::directory_iterator&, boost::system::error_code*)'
    /Users/username/.hunter/_Base/18cdbf5/7073908/6481172/Install/include/boost/filesystem/operations.hpp:903: error: undefined reference to 'boost::filesystem::detail::directory_iterator_construct(boost::filesystem::directory_iterator&, boost::filesystem::path const&, boost::system::error_code*)'
    /Users/username/.hunter/_Base/18cdbf5/7073908/6481172/Install/include/boost/filesystem/operations.hpp:868: error: undefined reference to 'boost::filesystem::detail::dir_itr_close(void*&, void*&)'
    /Users/username/.hunter/_Base/18cdbf5/7073908/6481172/Install/include/boost/filesystem/operations.hpp:868: error: undefined reference to 'boost::filesystem::detail::dir_itr_close(void*&, void*&)'
    /Users/username/workspace/fogofworld2/app/fogofworld/widgets/import/storage_import_card.cc:535: error: undefined reference to 'boost::filesystem::path::extension() const'
    /Users/username/workspace/fogofworld2/app/fogofworld/widgets/import/storage_import_card.cc:1016: error: undefined reference to 'boost::filesystem::path::parent_path() const'
    /Users/username/workspace/fogofworld2/app/fogofworld/widgets/import/storage_import_card.cc:1042: error: undefined reference to 'boost::filesystem::path::stem() const'
    /Users/username/workspace/fogofworld2/app/fogofworld/widgets/import/storage_import_card.cc:1044: error: undefined reference to 'boost::filesystem::path::extension() const'
    /Users/username/workspace/fogofworld2/app/fogofworld/widgets/import/storage_import_card.cc:1063: error: undefined reference to 'boost::filesystem::path::extension() const'
    /Users/username/workspace/fogofworld2/app/fogofworld/core/font.cc:204: error: undefined reference to 'boost::filesystem::path::stem() const'
    /Users/username/workspace/fogofworld2/app/fogofworld/core/font.cc:147: error: undefined reference to 'boost::filesystem::path::stem() const'
    /Users/username/.hunter/_Base/18cdbf5/7073908/6481172/Install/include/boost/system/error_code.hpp:449: error: undefined reference to 'boost::system::system_category()'
    /Users/username/.hunter/_Base/18cdbf5/7073908/6481172/Install/include/boost/filesystem/operations.hpp:550: error: undefined reference to 'boost::filesystem::detail::copy_file(boost::filesystem::path const&, boost::filesystem::path const&, boost::filesystem::detail::copy_option, boost::system::error_code*)'
    /Users/username/.hunter/_Base/18cdbf5/7073908/6481172/Install/include/boost/system/error_code.hpp:449: error: undefined reference to 'boost::system::system_category()'
    /Users/username/.hunter/_Base/18cdbf5/7073908/6481172/Install/include/boost/filesystem/operations.hpp:681: error: undefined reference to 'boost::filesystem::detail::rename(boost::filesystem::path const&, boost::filesystem::path const&, boost::system::error_code*)'
    /Users/username/workspace/fogofworld2/app/fogofworld/storages/local_storage.cc:149: error: undefined reference to 'boost::filesystem::path::filename() const'
    /Users/username/.hunter/_Base/18cdbf5/7073908/6481172/Install/include/boost/filesystem/operations.hpp:614: error: undefined reference to 'boost::filesystem::detail::file_size(boost::filesystem::path const&, boost::system::error_code*)'
    /Users/username/.hunter/_Base/18cdbf5/7073908/6481172/Install/include/boost/filesystem/operations.hpp:939: error: undefined reference to 'boost::filesystem::detail::directory_iterator_increment(boost::filesystem::directory_iterator&, boost::system::error_code*)'
    /Users/username/workspace/fogofworld2/app/fogofworld/storages/local_storage.cc:135: error: undefined reference to 'boost::filesystem::path::filename() const'
    /Users/username/.hunter/_Base/18cdbf5/7073908/6481172/Install/include/boost/filesystem/operations.hpp:614: error: undefined reference to 'boost::filesystem::detail::file_size(boost::filesystem::path const&, boost::system::error_code*)'
    /Users/username/.hunter/_Base/18cdbf5/7073908/6481172/Install/include/boost/filesystem/operations.hpp:550: error: undefined reference to 'boost::filesystem::detail::copy_file(boost::filesystem::path const&, boost::filesystem::path const&, boost::filesystem::detail::copy_option, boost::system::error_code*)'
    /Users/username/.hunter/_Base/18cdbf5/7073908/6481172/Install/include/boost/filesystem/operations.hpp:596: error: undefined reference to 'boost::filesystem::detail::current_path(boost::system::error_code*)'
    /Users/username/workspace/fogofworld2/fogofworld/model/model.cc:203: error: undefined reference to 'boost::filesystem::absolute(boost::filesystem::path const&, boost::filesystem::path const&)'
    /Users/username/.hunter/_Base/18cdbf5/7073908/6481172/Install/include/boost/filesystem/operations.hpp:939: error: undefined reference to 'boost::filesystem::detail::directory_iterator_increment(boost::filesystem::directory_iterator&, boost::system::error_code*)'
    /Users/username/workspace/fogofworld2/fogofworld/model/model.cc:738: error: undefined reference to 'boost::filesystem::path::filename() const'
    /Users/username/.hunter/_Base/18cdbf5/7073908/6481172/Install/include/boost/filesystem/operations.hpp:723: error: undefined reference to 'boost::filesystem::detail::unique_path(boost::filesystem::path const&, boost::system::error_code*)'
    /Users/username/.hunter/_Base/18cdbf5/7073908/6481172/Install/include/boost/filesystem/operations.hpp:723: error: undefined reference to 'boost::filesystem::detail::unique_path(boost::filesystem::path const&, boost::system::error_code*)'
    /Users/username/.hunter/_Base/18cdbf5/7073908/6481172/Install/include/boost/filesystem/operations.hpp:939: error: undefined reference to 'boost::filesystem::detail::directory_iterator_increment(boost::filesystem::directory_iterator&, boost::system::error_code*)'
    /Users/username/.hunter/_Base/18cdbf5/7073908/6481172/Install/include/boost/filesystem/operations.hpp:681: error: undefined reference to 'boost::filesystem::detail::rename(boost::filesystem::path const&, boost::filesystem::path const&, boost::system::error_code*)'
    /Users/username/.hunter/_Base/18cdbf5/7073908/6481172/Install/include/boost/filesystem/operations.hpp:681: error: undefined reference to 'boost::filesystem::detail::rename(boost::filesystem::path const&, boost::filesystem::path const&, boost::system::error_code*)'
    /Users/username/.hunter/_Base/18cdbf5/7073908/6481172/Install/include/boost/filesystem/operations.hpp:550: error: undefined reference to 'boost::filesystem::detail::copy_file(boost::filesystem::path const&, boost::filesystem::path const&, boost::filesystem::detail::copy_option, boost::system::error_code*)'
    /Users/username/.hunter/_Base/18cdbf5/7073908/6481172/Install/include/boost/filesystem/operations.hpp:723: error: undefined reference to 'boost::filesystem::detail::unique_path(boost::filesystem::path const&, boost::system::error_code*)'
    /Users/username/.hunter/_Base/18cdbf5/7073908/6481172/Install/include/boost/filesystem/operations.hpp:716: error: undefined reference to 'boost::filesystem::detail::temp_directory_path(boost::system::error_code*)'
    /Users/username/.hunter/_Base/18cdbf5/7073908/6481172/Install/include/boost/filesystem/operations.hpp:716: error: undefined reference to 'boost::filesystem::detail::temp_directory_path(boost::system::error_code*)'
    clang++: error: linker command failed with exit code 1 (use -v to see invocation)
    ninja: build stopped: subcommand failed.

To make sure this issue only happens for `x86_64`. I also set [abiFilters](https://google.github.io/android-gradle-dsl/current/com.android.build.gradle.internal.dsl.NdkOptions.html) to the other three: 'armeabi-v7a', 'arm64-v8a', 'x86'. And it passed the building process successfully without any error. How can I fix it? Thanks.

**Comment by ruslo** [comment]
What version of Hunter are you using? Have you tried to update? What is the logs with `HUNTER_STATUS_DEBUG=ON`? Basically try to follow this guide: https://docs.hunter.sh/en/latest/contributing.html#reporting-bugs
